parameters:
#    user_practice.example.class: User\PracticeBundle\Example

services:
#    user_practice.example:
#        class: %user_practice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
