User\PracticeBundle\Entity\User:
    properties:
        email:	
            - Email: 
                 message: Email {{ value }} in invalid
            - NotNull: {message: 'Please enter your email'}
        password:
            - NotBlank: ~
            - Length:
                 min: 3
                 max: 6
                 maxMessage: "Password must atleast {{ limit }} characters only"
        firstname:
            - NotBlank: ~
        lastname:
            - NotBlank: ~

