User\PracticeBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: text
        firstname:
            type: text
        lastname:
            type: text
        password:
            type: text
        status:
            type: boolean
        salt:
            type: text
        roles:
            type: text
    lifecycleCallbacks: {  }
