security:
    encoders:
        User\PracticeBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        user_db:
            entity: { class: User\PracticeBundle\Entity\User, property: email}

    firewalls:
        main:
            pattern: ^/
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                failure_path: /login
                default_target_path: /home
            logout:
                path: /logout
                target: /login
            security: true
            anonymous: true
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/signup, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/home, role: ROLE_USER}